### ISSUE TITLE
Goal Not Updating Correctly

### ISSUE THREAD

**Issue by Assyarul** [AY2021S2-CS2103T-W14-1/tp#118]
Replicate:
1. Get the default address book.
2. `add-meeting 1 d/30-03-2021 t/1010 desc/We had a sweet talk about sandwiches`
3. `set-goal 1 f\w`

Results:
1. Goal shows 'Yet to meet this person' instead of meeting the following week.

**Comment by ivantjh** [comment]
Fixed by #119
