### ISSUE TITLE
Successful adding of meeting and special date shows little feedback to user

### ISSUE THREAD

**Issue by ivantjh** [AY2021S2-CS2103T-W14-1/tp#147]
Currently, after adding of meeting and special date, the results display will indicate to the user that the operations executed were successful. The results display may not provide obvious enough feedback to the user. A suggestion is to switch to the currently added user's details panel after adding meeting and special date.

**Comment by chesterhow** [comment]
Closing as the implementation of this feature might lead to additional bugs, which is not ideal based on our timeline.
