### ISSUE TITLE
Adding invalid dates for add-meeting and add-dates

### ISSUE THREAD

**Issue by Assyarul** [AY2021S2-CS2103T-W14-1/tp#250]
Adding `d/30-02-2000` for example still goes through but details panel shows the date being corrected to 28 Feb.

Steps to replicate
1. Start FriendDex with the default data.
2. `details 1` to show the details panel for index 1.
3. `add-meeting 1 d/30-03-2021 t/1010 desc/We had a sweet talk about sandwiches`

**Comment by ivantjh** [comment]
`Localdate` parsing behaviour, the library will accept any numbers from 1 - 31 for `dayOfMonth` and will shift it to the last day of that month if the `dayofMonth` is out of range. 

E.g. 
```java
x.parse("31-06-2000", LocalDate::from) // 2000-06-30
x.parse("30-02-2004", LocalDate::from) // 2004-02-29 leap year
x.parse("30-02-2005", LocalDate::from) // 2005-02-28 not a leap year
```

**Comment by ivantjh** [comment]
Accept it for now -> reasoning given is that if a user enters `31-06-2000`, there is a high chance that they just want the last day of June. If it is not desired, they can remove the meeting/special date and change it.
